In [1]:
import pandas as pd
import numpy as np 
import json
import requests
from pandas.io.json import json_normalize
#!conda install -c conda-forge folium=0.5.0 --yes
import folium

from sklearn.cluster import KMeans
print("libraries imported")

libraries imported

In [9]:
results = pd.read_html("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
results

[    Postal code           Borough  \
 0           M1A      Not assigned
 1           M2A      Not assigned
 2           M3A        North York
 3           M4A        North York
 4           M5A  Downtown Toronto
 5           M6A        North York
 6           M7A  Downtown Toronto
 7           M8A      Not assigned
 8           M9A         Etobicoke
 9           M1B       Scarborough
 10          M2B      Not assigned
 11          M3B        North York
 12          M4B         East York
 13          M5B  Downtown Toronto
 14          M6B        North York
 15          M7B      Not assigned
 16          M8B      Not assigned
 17          M9B         Etobicoke
 18          M1C       Scarborough
 19          M2C      Not assigned
 20          M3C        North York
 21          M4C         East York
 22          M5C  Downtown Toronto
 23          M6C              York
 24          M7C      Not assigned
 25          M8C      Not assigned
 26          M9C         Etobicoke
 27          M1E       Scarborough
 28          M2E      Not assigned
 29          M3E      Not assigned
 ..          ...               ...
 150         M7W      Not assigned
 151         M8W         Etobicoke
 152         M9W         Etobicoke
 153         M1X       Scarborough
 154         M2X      Not assigned
 155         M3X      Not assigned
 156         M4X  Downtown Toronto
 157         M5X  Downtown Toronto
 158         M6X      Not assigned
 159         M7X      Not assigned
 160         M8X         Etobicoke
 161         M9X      Not assigned
 162         M1Y      Not assigned
 163         M2Y      Not assigned
 164         M3Y      Not assigned
 165         M4Y  Downtown Toronto
 166         M5Y      Not assigned
 167         M6Y      Not assigned
 168         M7Y      East Toronto
 169         M8Y         Etobicoke
 170         M9Y      Not assigned
 171         M1Z      Not assigned
 172         M2Z      Not assigned
 173         M3Z      Not assigned
 174         M4Z      Not assigned
 175         M5Z      Not assigned
 176         M6Z      Not assigned
 177         M7Z      Not assigned
 178         M8Z         Etobicoke
 179         M9Z      Not assigned

                                           Neighborhood
 0                                                  NaN
 1                                                  NaN
 2                                            Parkwoods
 3                                     Victoria Village
 4                           Regent Park / Harbourfront
 5                    Lawrence Manor / Lawrence Heights
 6         Queen's Park / Ontario Provincial Government
 7                                                  NaN
 8                                     Islington Avenue
 9                                      Malvern / Rouge
 10                                                 NaN
 11                                           Don Mills
 12                    Parkview Hill / Woodbine Gardens
 13                            Garden District, Ryerson
 14                                           Glencairn
 15                                                 NaN
 16                                                 NaN
 17   West Deane Park / Princess Gardens / Martin Gr...
 18            Rouge Hill / Port Union / Highland Creek
 19                                                 NaN
 20                                           Don Mills
 21                                    Woodbine Heights
 22                                      St. James Town
 23                                  Humewood-Cedarvale
 24                                                 NaN
 25                                                 NaN
 26   Eringate / Bloordale Gardens / Old Burnhamthor...
 27                 Guildwood / Morningside / West Hill
 28                                                 NaN
 29                                                 NaN
 ..                                                 ...
 150                                                NaN
 151                            Alderwood / Long Branch
 152                                          Northwest
 153                                        Upper Rouge
 154                                                NaN
 155                                                NaN
 156                       St. James Town / Cabbagetown
 157            First Canadian Place / Underground city
 158                                                NaN
 159                                                NaN
 160    The Kingsway / Montgomery Road / Old Mill North
 161                                                NaN
 162                                                NaN
 163                                                NaN
 164                                                NaN
 165                               Church and Wellesley
 166                                                NaN
 167                                                NaN
 168              Business reply mail Processing CentrE
 169  Old Mill South / King's Mill Park / Sunnylea /...
 170                                                NaN
 171                                                NaN
 172                                                NaN
 173                                                NaN
 174                                                NaN
 175                                                NaN
 176                                                NaN
 177                                                NaN
 178  Mimico NW / The Queensway West / South of Bloo...
 179                                                NaN

 [180 rows x 3 columns],
                                                   0   \
 0                                                NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NL
 3                                                  A

                                                   1   \
 0                              Canadian postal codes
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NS
 3                                                  B

                                                   2    3    4    5    6    7   \
 0                                                NaN  NaN  NaN  NaN  NaN  NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...  NaN  NaN  NaN  NaN  NaN
 2                                                 PE   NB   QC   QC   QC   ON
 3                                                  C    E    G    H    J    K

     8    9    10   11   12   13   14   15     16   17
 0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 2   ON   ON   ON   ON   MB   SK   AB   BC  NU/NT   YT
 3    L    M    N    P    R    S    T    V      X    Y  ,
    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15     16  17
 0  NL  NS  PE  NB  QC  QC  QC  ON  ON  ON  ON  ON  MB  SK  AB  BC  NU/NT  YT
 1   A   B   C   E   G   H   J   K   L   M   N   P   R   S   T   V      X   Y]

In [10]:
df=results[0]
df.head()

  Postal code           Borough                Neighborhood
0         M1A      Not assigned                         NaN
1         M2A      Not assigned                         NaN
2         M3A        North York                   Parkwoods
3         M4A        North York            Victoria Village
4         M5A  Downtown Toronto  Regent Park / Harbourfront

In [11]:
ndf=df.replace("Not assigned",np.nan)
ndf.head()

  Postal code           Borough                Neighborhood
0         M1A               NaN                         NaN
1         M2A               NaN                         NaN
2         M3A        North York                   Parkwoods
3         M4A        North York            Victoria Village
4         M5A  Downtown Toronto  Regent Park / Harbourfront

In [12]:
ndf=ndf.dropna(subset=['Borough'],axis=0)
ndf=ndf.reset_index()
df_sin_drop=ndf.drop('index',axis=1)
df_sin_drop.head()

  Postal code           Borough                                  Neighborhood
0         M3A        North York                                     Parkwoods
1         M4A        North York                              Victoria Village
2         M5A  Downtown Toronto                    Regent Park / Harbourfront
3         M6A        North York             Lawrence Manor / Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park / Ontario Provincial Government

In [13]:
#ndf.duplicated(ndf.columns[~ndf.columns.isin(['Postcode'])])
df_con_drop=df_sin_drop.drop_duplicates('Postal code')
df_con_drop=df_con_drop.reset_index()
df_con_drop=df_con_drop.drop('index',axis=1)
df_con_drop.head()

  Postal code           Borough                                  Neighborhood
0         M3A        North York                                     Parkwoods
1         M4A        North York                              Victoria Village
2         M5A  Downtown Toronto                    Regent Park / Harbourfront
3         M6A        North York             Lawrence Manor / Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park / Ontario Provincial Government

In [15]:

for n in range(0,len(df_con_drop)):#len(df_sin_drop)):
    for i in range(0,len(df_sin_drop)):
        if(df_con_drop.loc[n,'Postal code']== df_sin_drop.loc[i,'Postal code'] and df_con_drop.loc[n,'Neighborhood']!=df_sin_drop.loc[i,'Neighborhood']):
            df_con_drop.loc[n,'Neighborhood']=df_con_drop.loc[n,'Neighborhood']+","+df_sin_drop.loc[i,'Neighborhood']

In [17]:
df_con_drop.head(15)

,Postal code,Borough,Neighborhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,Regent Park / Harbourfront
3,M6A,North York,Lawrence Manor / Lawrence Heights
4,M7A,Downtown Toronto,Queen's Park / Ontario Provincial Government
5,M9A,Etobicoke,Islington Avenue
6,M1B,Scarborough,Malvern / Rouge
7,M3B,North York,Don Mills
8,M4B,East York,Parkview Hill / Woodbine Gardens
9,M5B,Downtown Toronto,"Garden District, Ryerson"
10,M6B,North York,Glencairn
11,M9B,Etobicoke,West Deane Park / Princess Gardens / Martin Gr...
12,M1C,Scarborough,Rouge Hill / Port Union / Highland Creek
13,M3C,North York,Don Mills
14,M4C,East York,Woodbine Heights

In [18]:
df_con_drop.shape

(103, 3)

In [382]:
conda install -c conda-forge geocoder

Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\emman\AppData\Local\Continuum\anaconda3

  added / updated specs:
    - geocoder


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    geocoder-1.38.1            |             py_1          53 KB  conda-forge
    ratelim-0.1.6              |             py_2           6 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          59 KB

The following NEW packages will be INSTALLED:

  geocoder           conda-forge/noarch::geocoder-1.38.1-py_1
  ratelim            conda-forge/noarch::ratelim-0.1.6-py_2



Downloading and Extracting Packages

ratelim-0.1.6        | 6 KB      |            |   0%
ratelim-0.1.6        | 6 KB      | ########## | 100%

geocoder-1.38.1      | 53 KB     |            |   0%
geocoder-1.38.1      | 53 KB     | ###        |  30%
geocoder-1.38.1      | 53 KB     | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Note: you may need to restart the kernel to use updated packages.

In [19]:
dfg=pd.read_csv("http://cocl.us/Geospatial_data")

In [10]:
dfg.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [20]:
df_con_drop['Latitude']=0
df_con_drop['Longitude']=0
df_con_drop.head()

,Postal code,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,0,0
1,M4A,North York,Victoria Village,0,0
2,M5A,Downtown Toronto,Regent Park / Harbourfront,0,0
3,M6A,North York,Lawrence Manor / Lawrence Heights,0,0
4,M7A,Downtown Toronto,Queen's Park / Ontario Provincial Government,0,0

In [21]:
dfg=dfg.rename(columns={"Postal Code":"Postcode"})
dfg.head()

  Postcode   Latitude  Longitude
0      M1B  43.806686 -79.194353
1      M1C  43.784535 -79.160497
2      M1E  43.763573 -79.188711
3      M1G  43.770992 -79.216917
4      M1H  43.773136 -79.239476

In [22]:
for i in range(0,len(dfg)):
    for n in range(0,len(df_con_drop)):
        if(dfg.loc[i,"Postcode"]==df_con_drop.loc[n,"Postal code"]):
            df_con_drop.loc[n,["Latitude","Longitude"]]=dfg.loc[i,["Latitude","Longitude"]]

In [23]:
df_con_drop.head()

,Postal code,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,Regent Park / Harbourfront,43.654260,-79.360636
3,M6A,North York,Lawrence Manor / Lawrence Heights,43.718518,-79.464763
4,M7A,Downtown Toronto,Queen's Park / Ontario Provincial Government,43.662301,-79.389494